Repository cse110-sp23-group22/FortuneTellingApp, pull requests merged in 2023-06, with the labels that each got.

#20 Update links in HP, README, add config in JSD WF
  .github/workflows/jsdocs.yaml
  README.md
  index.html
Labels: enhancement

#21 Horoscope form add to me
  .github/workflows/Questionnaire.yml
  .github/workflows/main.yml
  __test__/Q.test.js
  __tests__/simple.test.js
  source/Questionnaire/Questionnaire.js
  source/Questionnaire/testQuest-1.js
Labels: bug

#22 Horoscope display add to me
  .github/workflows/main.yml
  .gitignore
  __test__/horoscopeDisplay.test.js
  __test__/jest-puppeteer.config.js
  package-lock.json
  package.json
  source/HoroscopeDisplay/horoscope.html
  source/HoroscopeDisplay/horoscope.js
Labels: bug

#23 Tarot card display add to me
  index.html
  source/Questionnaire/Questionnaire.js
  source/TarotCardDisplay/TarotDisplay.html
  source/TarotCardDisplay/TarotDisplay.js
  source/TarotCardDisplay/TarotDisplayStyle.css
  source/styles.css
Labels: bug

#24 Fix scrolling on certain device screens
  index.html
  source/HomePage/HomePageStyle.css
  source/Styles.css
  source/TarotCardDisplay/TarotDisplayStyle.css
Labels: bug

#25 Questions on second page show up after first click
  source/TarotForm/TarotForm.html
  source/TarotForm/TarotForm.js
Labels: enhancement

#29 Resolve text clarity issue on HP
  index.html
  source/HomePage/CreditPageStyle.css
  source/HomePage/CreditsPage.html
  source/HomePage/HomePageStyle.css
Labels: enhancement

#28 Horoscope display add to me
  .gitignore
  __test__/HoroscopeDisplayE2E.test.js
  __test__/TarotCardDispalyE2E.test.js
  __test__/horoscopeDiplayUnitTesting.test.js
  source/Assets/Book.png
  source/HoroscopeDisplay/DisplayStyles.css
  source/HoroscopeDisplay/Horoscope.js
  source/HoroscopeDisplay/horoscope.JSON
  source/HoroscopeQuestionnaire/HoroscopeQuestionnaire.html
  source/HoroscopeQuestionnaire/HoroscopeQuestionnaire.js
  source/HoroscopeQuestionnaire/HoroscopeQuestionnaireStyle.css
  source/Styles.css
  source/TarotForm/TarotForm.html
  source/TarotForm/TarotFormStyles.css
Labels: enhancement

#33 Horoscope form Documentation/Comments
  source/HoroscopeQuestionnaire/HoroscopeQuestionnaire.html
  source/HoroscopeQuestionnaire/HoroscopeQuestionnaire.js
  source/HoroscopeQuestionnaire/HoroscopeQuestionnaireStyle.css
  source/TarotForm/TarotForm.html
  source/TarotForm/TarotForm.js
  source/TarotForm/TarotFormStyles.css
Labels: documentation
